# Recommendation System

Data Description:  

Unique ID of each anime.   
Anime title.  
Anime broadcast type, such as TV, OVA, etc.  
anime genre.  
The number of episodes of each anime.  
The average rating for each anime compared to the number of users who gave ratings.  


Number of community members for each anime.  
Objective:  
The objective of this assignment is to implement a recommendation system using cosine similarity on an anime dataset.   
Dataset:  
Use the Anime Dataset which contains information about various anime, including their titles, genres,No.of episodes and user ratings etc.

## Tasks:     

## 1.Data Preprocessing:      

Load the dataset into a suitable data structure (e.g., pandas DataFrame).      
Handle missing values, if any.     
Explore the dataset to understand its structure and attributes.

In [1]:
# Load the dataset 
import pandas as pd 

df = pd.read_csv("anime.csv")

In [2]:
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [3]:
# Check Missing Values 
missing = pd.DataFrame({
    "Missing" : df.isnull().sum(),
        "Percentage" : (df.isnull().sum() /len(df)) * 100
})

missing.sort_values("Missing",ascending = False)

          Missing  Percentage
rating        230    1.870831
genre          62    0.504311
type           25    0.203351
anime_id        0    0.000000
name            0    0.000000
episodes        0    0.000000
members         0    0.000000

In [4]:
# Handle Missing Values 
cat_cols = df.select_dtypes(include = 'object').columns
num_cols = df.select_dtypes(include = ['int','float']).columns
from sklearn.impute import SimpleImputer
df[cat_cols]  = SimpleImputer(strategy= 'most_frequent').fit_transform(df[cat_cols])
df[num_cols] = SimpleImputer(strategy = 'mean').fit_transform(df[num_cols])

In [5]:
# Verify Missing Values 
missing = pd.DataFrame({
    "Missing" : df.isnull().sum(),
        "Percentage" : (df.isnull().sum() /len(df)) * 100
})

missing.sort_values("Missing",ascending = False)

          Missing  Percentage
anime_id        0         0.0
name            0         0.0
genre           0         0.0
type            0         0.0
episodes        0         0.0
rating          0         0.0
members         0         0.0

In [6]:
# Check Duplicates 
df.duplicated().sum()

np.int64(0)

In [7]:
# Head of the Dataset 
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281.0,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630.0
1,5114.0,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665.0
2,28977.0,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262.0
3,9253.0,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572.0
4,9969.0,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266.0

In [8]:
# Tail of the Dataset 
df.tail()

,anime_id,name,genre,type,episodes,rating,members
12289,9316.0,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211.0
12290,5543.0,Under World,Hentai,OVA,1,4.28,183.0
12291,5621.0,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219.0
12292,6133.0,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175.0
12293,26081.0,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142.0

In [9]:
# Dataset columns 
df.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [10]:
# Dataset Shape
df.shape

(12294, 7)

In [11]:
# General Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  float64
 1   name      12294 non-null  object
 2   genre     12294 non-null  object
 3   type      12294 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12294 non-null  float64
 6   members   12294 non-null  float64
dtypes: float64(3), object(4)
memory usage: 672.5+ KB

In [12]:
# StatisticalSummary 
df.describe()

           anime_id        rating       members
count  12294.000000  12294.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.017096  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.900000  2.250000e+02
50%    10260.500000      6.550000  1.550000e+03
75%    24794.500000      7.170000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [13]:
# Anime Unique id 
df.anime_id.nunique()

12294

In [14]:
# Anime unique name 
df.name.nunique()

12292

In [15]:
# Unique Rating 
df['members'].nunique()

6706

In [16]:
# Average Ratings of Anime 
df.groupby('name')['rating'].mean().sort_values(ascending = False)

name
Taka no Tsume 8: Yoshida-kun no X-Files    10.00
Spoon-hime no Swing Kitchen                 9.60
Mogura no Motoro                            9.50
Kimi no Na wa.                              9.37
Kahei no Umi                                9.33
                                           ...
Hametsu no Mars                             2.37
Utsu Musume Sayuri                          2.14
Tenkuu Danzai Skelter+Heaven                2.00
Hi Gekiga Ukiyoe Senya Ichiya               1.92
Platonic Chain: Ansatsu Jikkouchuu          1.67
Name: rating, Length: 12292, dtype: float64

In [17]:
# Rating Value Counts 
df.rating.value_counts().sort_values(ascending = False)

rating
6.473902    230
6.000000    141
7.000000     99
6.500000     90
6.250000     84
           ...
9.330000      1
8.690000      1
8.720000      1
8.740000      1
3.140000      1
Name: count, Length: 599, dtype: int64

## 2.Feature Extraction:     

Decide on the features that will be used for computing similarity (e.g., genres, user ratings).     
Convert categorical features into numerical representations if necessary.     
Normalize numerical features if required.

In [18]:
# Feature Extraction 
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words = 'english')

genre_matrix = vectorizer.fit_transform(df['genre'])

## 3.Recommendation System:     
Design a function to recommend anime based on cosine similarity.     
Given a target anime, recommend a list of similar anime based on cosine similarity scores.      
Experiment with different threshold values for similarity scores to adjust the recommendation list size.       
Analyze the performance of the recommendation system and identify areas of improvement.

In [19]:
# Compute cosine Similarity 
from sklearn.metrics.pairwise import cosine_similarity
cosin_sim = cosine_similarity(genre_matrix)

In [20]:
# Create index mapping 
indices = pd.Series(df.index, index = df['name']).drop_duplicates()

In [21]:
# Recommendation Function 
def recommend_anime (anime_name, top_n = 10):

    if anime_name not in indices:
        return "Anime not found!!"

        
    idx = indices[anime_name]
    similarity_scores = list(enumerate(cosin_sim[idx]))

    similarity_scores = sorted(
        similarity_scores,
        key = lambda x: x[1],
        reverse = True
    )

    similarity_scores = similarity_scores[0:top_n+1]
    anime_indices = [i[0] for i in similarity_scores]

    return df.iloc[anime_indices][['name','genre','rating']].sort_values('rating',ascending = False)

In [22]:
# Recommended Anime 
recommend_anime('Kimi no Na wa.')

,name,genre,rating
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural",9.37
208,Kokoro ga Sakebitagatterunda.,"Drama, Romance, School",8.32
504,"Clannad: After Story - Mou Hitotsu no Sekai, K...","Drama, Romance, School",8.02
1111,Aura: Maryuuin Kouga Saigo no Tatakai,"Comedy, Drama, Romance, School, Supernatural",7.67
1201,Angel Beats!: Another Epilogue,"Drama, School, Supernatural",7.63
1435,True Tears,"Drama, Romance, School",7.55
1436,&quot;Bungaku Shoujo&quot; Memoire,"Drama, Romance, School",7.54
1494,Harmonie,"Drama, School, Supernatural",7.52
1631,Kimikiss Pure Rouge,"Drama, Romance, School",7.48
5805,Wind: A Breath of Heart OVA,"Drama, Romance, School, Supernatural",6.35
6394,Wind: A Breath of Heart (TV),"Drama, Romance, School, Supernatural",6.14

In [23]:
# Treshold Recommendation 

def recommend_treshold(anime_name, treshold = 0.4):
    if anime_name not in indices:
        return "Anime Not Found!!!"

    idx = indices[anime_name]
    similarity_scores = list(enumerate(cosin_sim[idx]))

    filtered = []

    for i , score in similarity_scores:

        if score >= treshold and i != idx:
            filtered.append((i, score))

    filtered = sorted(filtered,
                     key = lambda x: x[1],
                     reverse = True
                     )
    anime_indices = [i[0] for i in filtered]


    return df.iloc[anime_indices][
        ['name','genre','rating','episodes']
    ]

In [24]:
recommend_treshold("Kimi no Na wa.", 0.05)

,name,genre,rating,episodes
5805,Wind: A Breath of Heart OVA,"Drama, Romance, School, Supernatural",6.35,3
6394,Wind: A Breath of Heart (TV),"Drama, Romance, School, Supernatural",6.14,13
1111,Aura: Maryuuin Kouga Saigo no Tatakai,"Comedy, Drama, Romance, School, Supernatural",7.67,1
208,Kokoro ga Sakebitagatterunda.,"Drama, Romance, School",8.32,1
504,"Clannad: After Story - Mou Hitotsu no Sekai, K...","Drama, Romance, School",8.02,1
...,...,...,...,...
10696,Video Ehonkan Sekai Meisaku Douwa,"Adventure, Comedy, Fantasy, Historical, Kids, ...",5.57,26
4230,Betterman,"Action, Adventure, Comedy, Drama, Horror, Mech...",6.77,26
4432,Bakuretsu Hunters OVA,"Action, Adventure, Comedy, Ecchi, Fantasy, Har...",6.72,3
5203,Demashita! Powerpuff Girls Z,"Action, Comedy, Magic, School, Sci-Fi, Shoujo,...",6.52,52
10108,Sabu to Ichi Torimono Hikae,"Action, Adventure, Drama, Historical, Martial ...",7.10,52

## 4.Interview Questions:     
**1. Can you explain the difference between user-based and item-based collaborative filtering?**  
2. | Feature                  | User-Based                       | Item-Based                                |
| ------------------------ | -------------------------------- | ----------------------------------------- |
| Finds similarity between | **Users**                        | **Items**                                 |
| Recommendation based on  | Similar users                    | Similar items                             |
| Example                  | "Users like you also liked..."   | "Because you liked this, you may like..." |
| Main focus               | User preferences                 | Item relationships                        |
| Scalability              | Can be difficult with many users | Often more scalable                       |
| Stability                | User preferences can change      | Item relationships tend to be more stable |

**2. What is collaborative filtering, and how does it work?**  
Collaborative Filtering (CF) is a recommendation-system technique that recommends items to users based on the preferences and behavior of other users.  
Collaborative filtering recommends items by analyzing interactions between users and items and using similarities in those interactions to predict what a user may prefer.  
A typical collaborative filtering system follows these steps:  
User-Item Data
      ↓
Analyze user preferences
      ↓
Find similar users OR similar items
      ↓
Predict what the user may like
      ↓
Generate recommendations