# BASIC STATISTICS-2 :    


**Problem Statement : Hospital Patient Data Analysis**  
Context:  
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.
Tasks:  
1.	Load the patient dataset and show summary with info().  
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].  
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].  
4.	Use groupby to find total bill amount per department.  
5.	Remove duplicate patient records based on PatientID.  
6.	Fill missing BillAmount values with the mean bill amount.    
7.	Merge the billing dataset with patient dataset on PatientID.  
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).  
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).  
**Expected Outcome:**    
•	Final cleaned dataset with accurate billing info.  
•	All missing values handled, merged dataset across PatientID.   
•	Ability to perform further analytics on department-wise revenue or doctor performance.

In [44]:
# 1. Load the patient dataset and show summary with info().
import pandas as pd 

df = pd.read_csv("Patient_Data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [45]:
# 2. Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
relavent_col = df[['PatientID','Name','Department','BillAmount']]

In [46]:
# 3. Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
df.drop(columns = df[['ReceptionistID','CheckInTime']], inplace = True)

In [47]:
# 4. Use groupby to find total bill amount per department.
df.groupby('Department', as_index=False)['BillAmount'].sum()

    Department  BillAmount
0   Cardiology     16200.0
1  Dermatology         0.0
2    Neurology         0.0
3  Orthopedics      7500.0

In [48]:
# Check duplicates values
df.duplicated().sum()

np.int64(1)

In [49]:
# 5. Remove duplicate patient records based on PatientID.
df.drop_duplicates(inplace = True)

In [50]:
# Verify 
df.duplicated().sum()

np.int64(0)

In [51]:
# Check Missing values
df.isnull().sum()

PatientID     0
Name          0
Department    0
Doctor        0
BillAmount    2
dtype: int64

In [54]:
# 6. Fill missing BillAmount values with the mean bill amount. 
import numpy as np 
df.fillna(np.mean(df['BillAmount']), inplace = True)

In [57]:
# Verify
df.isnull().sum()

PatientID     0
Name          0
Department    0
Doctor        0
BillAmount    0
dtype: int64

In [76]:
# 7. Merge the billing dataset with patient dataset on PatientID.

df2 = pd.read_csv("Patient_Data.csv")

merged_df = pd.merge(df, df2, on="PatientID" )
merged_df

,PatientID,Name_x,Department_x,Doctor_x,BillAmount_x,Name_y,Department_y,Doctor_y,BillAmount_y,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.000000,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,101,Alice,Cardiology,Dr. Smith,5000.000000,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
2,102,Bob,Neurology,Dr. John,6233.333333,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
3,103,Charlie,Orthopedics,Dr. Lee,7500.000000,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
4,104,David,Cardiology,Dr. Smith,6200.000000,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
5,105,Eva,Dermatology,Dr. Rose,6233.333333,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [88]:
# 8. Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
new_patients = pd.DataFrame({
    "PatientID": [106, 107],
    "Name": ["Frank", "Grace"],
    "Department": ["Pediatrics", "Neurology"],
    "Doctor": ["Dr. Kumar", "Dr. John"],
    "BillAmount": [4500, 6800]
})
updated_df = pd.concat([df, new_patients], axis=0, ignore_index=True)

updated_df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        106    Frank   Pediatrics  Dr. Kumar  4500.000000
6        107    Grace    Neurology   Dr. John  6800.000000

In [92]:
# 9. Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
new_columns = pd.DataFrame({
    "InsuranceCovered": [2000, 1500, 3000, 2500, 1000],
    "FinalAmount": [5200, 7733, 7800, 8700, 7233]
})
updated_df = pd.concat([df, new_columns], axis=1)

updated_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,5200
1,102,Bob,Neurology,Dr. John,6233.333333,1500,7733
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,3000,7800
3,104,David,Cardiology,Dr. Smith,6200.000000,2500,8700
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,7233